<#
.SYNOPSIS
    Management script based on PowerShell, this script must be executed from the root directory.
#>

# [Initializations] ####################################################################################################
param (
    # Command to execute, one of:
    #    'load': Host/Container command, loads the Powershell modules in the terminal for more granular access.
    #    'clean': Host/Container command, recursively cleans the repository and submodules with Git.
    #    'build': Host command, builds the images and the development containers.
    #    'run': Host command creates or uses an existing development container and starts it in the current folder.
    #    'pylint': Container command, runs 'pylint' project wide.
    #    'pyright': Container command, runs 'pyright' project wide.
    #    'black': Container command, runs 'black' project wide.
    #    'doc8': Container command, runs 'doc8' project wide.
    #    'docs': Container command, runs 'sphinx' project wide.
    #    'scrapy': Container command, runs 'scrapy' commands.
    [Parameter(Mandatory = $true)]
    [ValidateSet(
        "load", "clean", "build", "run", "pylint", "pyright", "black", "doc8", "docs", "scrapy"
    )]
    [String]
    $Command,

    # Other arguments supplied.
    [Parameter(Mandatory = $false, ValueFromRemainingArguments = $true)]
    [String[]]
    $Args = @()
)

# Stop on first error found.
$ErrorActionPreference = "Stop";

# If the 'powershell_scripts' folder does not exist, shallow clone the latest version of the repository.
$cloneDir = "$PSScriptRoot/other/powershell_scripts";
if (-not (Test-Path "$cloneDir"))
{
    & "git" clone --branch "master" --depth 1 --shallow-submodules --recurse-submodules `
        "https://github.com/dmg0345/powershell_scripts" "$cloneDir";
    if ($LASTEXITCODE -ne 0)
    {
        throw "Failed to clone Git repository with the PowerShell scripts.";
    }
}

# Imports.
Import-Module "$PSScriptRoot/other/powershell_scripts/modules/commons.psm1";
Import-Module "$PSScriptRoot/other/powershell_scripts/modules/devcontainers.psm1";
Import-Module "$PSScriptRoot/other/powershell_scripts/modules/linters.psm1";
Import-Module "$PSScriptRoot/other/powershell_scripts/modules/documentation.psm1";

# [Declarations] #######################################################################################################
# Path to 'devcontainer.json' file.
$DEVCONTAINER_FILE = ".devcontainer/devcontainer.json"; 
# Project name for the Docker compose project.
$DEVCONTAINER_PROJECT_NAME = "scrapy_tor_playwright_demo";

# [Internal Functions] #################################################################################################

# [Functions] ##########################################################################################################

# [Execution] ##########################################################################################################
# Ensure the current location is the location of the script.
if (((Get-Item "$PSScriptRoot").Hashcode) -ne ((Get-Item "$PWD").Hashcode))
{
    throw "The script must run from the root directory, where this script is located."
}

if ($Command -eq "load")
{
    # The modules have already been imported due to the imports above, perform no other action.
    Write-Log "Modules imported." "Success";
}
elseif ($Command -eq "clean")
{
    Write-Log "Cleaning repository and submodules...";
    git clean -d -fx -f;
    git submodule foreach --recursive git clean -d -fx -f;
    Write-Log "Repository and submodules cleaned." "Success";
}
elseif ($Command -eq "build")
{
    # Build inputs for the development container.
    $inputs = @{};

    # Build outputs for the development container.
    $outputs = @{
        # This is the 'poetry.lock' file generated by Python environment, with all the dependencies.
        "Python Poetry lock file" = @{
            "containerPath" = "/usr/venvs/poetry.lock";
            "hostPath"      = "poetry.lock";
        }
    };
    
    Initialize-DevContainer -DevcontainerFile "$DEVCONTAINER_FILE" -ProjectName "$DEVCONTAINER_PROJECT_NAME" `
        -Inputs $inputs -Outputs $outputs;
}
elseif ($Command -eq "run")
{
    # Artifacts to copy in the workspace for the initialization script.
    $inputs = @{
        # This is the host path to Git authentication key.
        # 
        # This can't be provided as a secret in the Compose file as it needs specific permissions for it to be
        # trusted by the SSH utilities, and Compose does not do that, thus we copy it here and set the permissions
        # explicitly from the initialization script.
        "Git Authentication Key" = @{
            "hostPath" = "../!local/other-files/github/dmg0345-authentication-key/private-authentication-key.pem";
        };

        # This is the host path to Git signing key to sign commits.
        # 
        # This can't be provided as a secret in the Compose file as it needs specific permissions for it to be
        # trusted by the SSH utilities, and Compose does not do that, thus we copy it here and set the permissions
        # explicitly from the initialization script.
        "Git Signing Key"        = @{
            "hostPath" = "../!local/other-files/github/dmg0345-signing-key/private-signing-key.pem";
        };
    };
    
    # Create initialization script for the volume of the development container.
    $initScript = @'
# Configure Git for user.
git config --global user.name "$ENV:GITHUB_USERNAME";
git config --global user.email "$ENV:GITHUB_EMAIL";
git config --global user.signingkey "/vol_store/private-signing-key.pem";
git config --global core.sshCommand "ssh -i '/vol_store/private-authentication-key.pem' -o 'IdentitiesOnly yes'";

# Own and set permissions of the keys to read/write for SSH to use them.
Get-ChildItem -Path "/vol_store" -Include "*.pem" -Recurse | ForEach-Object -Process `
{
    chown $(id -u -n) "$($_.FullName)";
    chmod 600 "$($_.FullName)";
}

# Trust Github for SSH connections.
if (-not (Test-Path "~/.ssh/known_hosts")) { New-Item -Path "~/.ssh/known_hosts" -ItemType File -Force | Out-Null; }
Set-Content -Path "~/.ssh/known_hosts" -Value "$(ssh-keyscan github.com)" -Force;

# Clone repository in the workspace folder.
git clone --recurse-submodules --branch develop "git@github.com:dmg0345/scrapy-tor-playwright-demo.git" ".";
if ($LASTEXITCODE -ne 0) { throw "Failed to clone repository." }
'@;

    Start-DevContainer -DevcontainerFile "$DEVCONTAINER_FILE" -ProjectName "$DEVCONTAINER_PROJECT_NAME" `
        -VolumeInitScript $initScript -Inputs $inputs;
}
elseif ($Command -eq "pylint")
{
    $inputs = @("src", "tests");

    Start-Pylint -PylintExe "pylint" -ConfigFile "pyproject.toml" -Inputs $inputs;
}
elseif ($Command -eq "pyright")
{
    $inputs = @(".");

    Start-Pyright -PyrightExe "pyright" -ConfigFile "pyproject.toml" -Inputs $inputs;
}
elseif ($Command -eq "black")
{
    $inputs = @(".");

    Start-Black -BlackExe "black" -ConfigFile "pyproject.toml" -Inputs $inputs;
}
elseif ($Command -eq "doc8")
{
    # Build list of files and folders.
    $inputs = @(
        "src",
        "tests",
        "doc",
        "readme.rst"
    );

    Start-Doc8 -Doc8Exe "doc8" -ConfigFile "pyproject.toml" -Inputs $inputs;
}
elseif ($Command -eq "docs")
{
    Start-Sphinx -SphinxBuildExe "sphinx-build" -ConfigFolder "doc" -HTMLOutput "doc/.output/html";
}
elseif ($Command -eq "scrapy")
{
    # Move to the location of the Scrapy project, as it expects to be executed from the location of its config file.
    # Note this requires a virtual environment to be active, and the command to be passed in the following format:
    # ./manage.ps1 scrapy crawl quotes `-a mode='nojs'
    Push-Location "$PSScriptRoot\src";
    try 
    {
        Invoke-Expression "scrapy $($args -join " ")";
    }
    finally
    {
        # Restore the original location after execution of Scrapy finished.
        Pop-Location;
    }
}
else
{
    throw "Command '$Command' is not recognized or an invalid combination of arguments was provided.";
}
